czaswolny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.forms import *
from userena import views as userena_views
from reputation import views as reputation_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/signup/$', userena_views.signup, {'signup_form': SignupFormExtra}, name='userena_signup'),
    url(r'^accounts/signin/$', userena_views.signin, {'auth_form': AuthenticationFormExtra}, name='userena_signin'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/edit/$', userena_views.profile_edit, {'edit_profile_form': EditProfileFormExtra}, name='userena_profile_edit'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/$', reputation_views.show_received, name='reputation_show_received'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/given/$', reputation_views.show_given, name='reputation_show_given'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/add/$', reputation_views.add, name='reputation_add'),
    url(r'^accounts/', include('userena.urls')),
    url(r'^events/', include('events.urls'), name='events'),
    url(r'^accounts/addfriend/(?P<pk>[0-9]+)/$', views.addfriend, name='addfriend'),
    url(r'^accounts/invite/(?P<pk>[0-9]+)/$', views.invite, name='invite'),
    url(r'^accounts/refuseinvite/(?P<pk>[0-9]+)/$', views.refuseinvite, name='refuseinvite'),
    url(r'^accounts/unfriend/(?P<pk>[0-9]+)/$', views.unfriend, name='unfriend'),
    url(r'^accounts/uninvite/(?P<pk>[0-9]+)/$', views.uninvite, name='uninvite'),
    url(r'^posts/', include('posts.urls'), name='posts'),
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^observing/$', views.observing, name='observing'),
    url(r'^show/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^destroy/(?P<pk>[0-9]+)/$', views.destroy, name='destroy'),
    url(r'^join/(?P<pk>[0-9]+)/$', views.join, name='join'),
    url(r'^leave/(?P<pk>[0-9]+)/$', views.leave, name='leave'),
    url(r'^observe/(?P<pk>[0-9]+)/$', views.observe, name='observe'),
    url(r'^stopobserving/(?P<pk>[0-9]+)/$', views.stop_observing, name='stop_observing'),
    url(r'^block/(?P<pk>[0-9]+)/(?P<user_id>[0-9]+)/$', views.block, name='block'),
    url(r'^unblock/(?P<pk>[0-9]+)/(?P<user_id>[0-9]+)/$', views.unblock, name='unblock'),
    url(r'^create/$', views.create, name='create'),
    url(r'^like/(?P<pk>[0-9]+)/$', views.like, name='like'),
    url(r'^unlike/(?P<pk>[0-9]+)/$', views.unlike, name='unlike'),

]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/(?P<pk>[0-9]+)/$', views.create, name='create'),
    url(r'^show/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^destroy/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.destroy, name='destroy'),
    url(r'^destroycomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/(?P<pk3>[0-9]+)/$', views.destroycomment, name='destroycomment'),
    url(r'^createcomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.createcomment, name='createcomment'),
    url(r'^like/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.like, name='like'),
    url(r'^unlike/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.unlike, name='unlike'),

]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post
from taggit.managers import TaggableManager

# https://docs.djangoproject.com/en/1.11/ref/models/fields/#manytomany-arguments
# https://docs.djangoproject.com/en/1.11/topics/db/examples/many_to_many/


class Event(models.Model):
    name = models.CharField(max_length=50, blank=False)
    description = models.TextField(max_length=4000, blank=False)
    start_date = models.DateTimeField(blank=False)
    end_date = models.DateTimeField(blank=False)
    place_text = models.CharField(max_length=80, blank=False)
    place_location_lat = models.FloatField(blank=False)
    place_location_lng = models.FloatField(blank=False)
    users = models.ManyToManyField(User)
    posts = models.ManyToManyField(Post)
    author = models.ForeignKey(User, related_name="autor")
    tags = TaggableManager(blank=True)
    likes = models.ManyToManyField(User, related_name="likes")
    blacklist = models.ManyToManyField(User, related_name="blacklist")

    def __str__(self):
        return self.name


"""
class EventUser(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
"""

events/forms.py
from django import forms
from .models import Event
from taggit.models import Tag
from django.core.exceptions import ValidationError


class EventForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False, widget=forms.CheckboxSelectMultiple(), to_field_name='name')
    place_location_lat = forms.FloatField(widget=forms.HiddenInput(), required=True)
    place_location_lng = forms.FloatField(widget=forms.HiddenInput(), required=True)
    start_date = forms.DateField(label='Start date', widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='End date', widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    def clean(self):
        if (self.cleaned_data['start_date'] >
            self.cleaned_data['end_date']):
            raise ValidationError("Event's end date can't be before start date !")

        return self.cleaned_data

    class Meta:
        model = Event

        fields = ('name', 'description', 'start_date', 'end_date', 'tags', 'place_text', 'place_location_lat', 'place_location_lng',)
        labels = {"name": "Name",
                  "description": "Description",
                  "place_text": "Place",
                  }

events/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import EventForm
from .models import Event
from django.contrib import messages
from notify.signals import notify
from accounts.models import MyProfile
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from czaswolny.decorators import user_not_banned
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



@login_required
@user_not_banned
def index(request):
    events_all = Event.objects.all().order_by('-start_date')

    # Paginacja co 5 wydarze
    paginator = Paginator(events_all, 5)
    page = request.GET.get('page', 1)
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        events = paginator.page(1)
    except EmptyPage:
        events = paginator.page(paginator.num_pages)

    return render(request, 'events/index.html', {'events': events})


@login_required
@user_not_banned
def observing(request):
    profile = get_object_or_404(MyProfile, user_id=request.user.my_profile.user_id)

    events = profile.observing_events.all()

    return render(request, 'events/observing.html', {'events': events})




@login_required
@user_not_banned
def create(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.save()
            # ponizsza linijka na potrzeby zapisu tagow
            form.save_m2m()
            return redirect('events:details', pk=event.pk)
    else:
        form = EventForm()
    return render(request, 'events/create.html', {'form': form})



@require_POST
@login_required
@user_not_banned
def destroy(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    event = get_object_or_404(Event, pk=pk)
    if request.user != event.author:
        return HttpResponseRedirect(reverse('events:index'))
    if event.users.all().exists():
        notify.send(request.user, recipient_list=list(event.users.all()), actor=request.user, verb='deleted event you had joined.', nf_type='event_deleted')
    event.delete()
    return redirect('events:index')


@login_required
@user_not_banned
def details(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk)

    posts_all = event.posts.all().order_by('-publish_date')
    # Paginacja co 5 postow
    posts_paginator = Paginator(posts_all, 5)
    posts_page = request.GET.get('posts-page', 1)
    try:
        posts = posts_paginator.page(posts_page)
    except PageNotAnInteger:
        posts = posts_paginator.page(1)
    except EmptyPage:
        posts = posts_paginator.page(posts_paginator.num_pages)

    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def join(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    event = get_object_or_404(Event, pk=pk)

    if request.user in event.blacklist.all():
        return HttpResponseRedirect(reverse('events:index'))

    event.users.add(request.user)
    if request.user != event.author:
        notify.send(request.user, recipient=event.author, actor=request.user, verb='joined your event.', nf_type='event_user_joined')

    if request.user not in event.blacklist.all():
        event.users.add(request.user)
    posts = event.posts.all

    if request.user.pk in Event.objects.values_list('users', flat=True):
        messages.success(request, 'Event joined')

    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def observe(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    event = get_object_or_404(Event, pk=pk)

    if request.user in event.blacklist.all():
        return HttpResponseRedirect(reverse('events:index'))
    profile = get_object_or_404(MyProfile, user_id=request.user.my_profile.user_id)
    profile.observing_events.add(event)

    posts = event.posts.all

    if request.user.pk in Event.objects.values_list('users', flat=True):
        messages.success(request, 'Event added to your observed events')

    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def stop_observing(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk)
    profile = get_object_or_404(MyProfile, user_id=request.user.my_profile.user_id)
    profile.observing_events.add(event)

    profile.observing_events.remove(event)
    posts = event.posts.all
    messages.success(request, 'Event removed from observed events')
    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def leave(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk)
    event.users.remove(request.user)
    posts = event.posts.all
    messages.success(request, 'Wypisano z eventu')
    return render(request, 'events/details.html', {'event': event, 'posts': posts})

@login_required
@user_not_banned
def unblock(request, pk, user_id):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk)
    if request.user != event.author:
        return HttpResponseRedirect(reverse('events:index'))
    user = get_object_or_404(MyProfile, user_id = user_id)
    event.blacklist.remove(user.user)
    posts = event.posts.all
    messages.success(request, 'Usunieto z blacklisty')
    return render(request, 'events/details.html', {'event': event, 'posts': posts})

@require_POST
@login_required
@user_not_banned
def block(request, pk, user_id):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk)

    if request.user != event.author:
        return HttpResponseRedirect(reverse('events:index'))

    user = get_object_or_404(get_user_model(), id=user_id)
    event.blacklist.add(user)

    posts = event.posts.all
    event.users.remove(user)
    messages.success(request, 'Usunieto uzytkownika z eventu')
    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def like(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    event = get_object_or_404(Event, pk=pk)
    event.likes.add(request.user)
    posts = event.posts.all
    return render(request, 'events/details.html', {'event': event, 'posts': posts})


@require_POST
@login_required
@user_not_banned
def unlike(request, pk):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    event = get_object_or_404(Event, pk=pk)
    event.likes.remove(request.user)
    posts = event.posts.all
    return render(request, 'events/details.html', {'event': event, 'posts': posts})

events/templates/events/create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Tworzenie wydarzenia{% endblock %}
{% block content_title %}New Event{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'events/googlemaps.css' %}" />
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>"{{field.name}}" {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
    <form class="row" method="POST" class="post-form">{% csrf_token %}
      <div class="panel">
        <div class="panel-body">
          <div class="col-md-5">
              <div class="form-group">
                  <label class="bmd-label-floating">Name</label>
                  {{ form.name|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: Event name" }}
                  {{ form.name.errors }}
              </div>
              <div class="form-group">
                  <label class="bmd-label-floating">Description</label>
                  {{ form.description|add_class:"form-control rounded-0 py-2" }}
                  {{ form.description.errors }}
              </div>
              <div class="form-group">
                  <label class="bmd-label-floating">Start date</label>
                  {{ form.start_date|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: Start date" }}
                  {{ form.start_date.errors }}
              </div>
              <div class="form-group">
                  <label class="bmd-label-floating">End date</label>
                  {{ form.end_date|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: End date" }}
                  {{ form.end_date.errors }}
              </div>
              <div class="form-group">
                  <label class="bmd-label-floating">Place</label>
                  {{ form.place_text|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: Place" }}
                  {{ form.place_text.errors }}
              </div>
              <button type="submit" class="btn btn-primary">Add Event</button>
          </div>
          <div class="col-md-7">
              <div class="card row card-content map_canvas"></div>
              <input class="form-control" id="geocomplete" type="text" placeholder="Type in an address" value="Polska, Białystok" />
              <input class="btn btn-primary btn-sm" id="find" type="button" value="Find on map" />
          </div>
          <input type="hidden" name="place_location_lat" id="id_place_location_lat" />
          <input type="hidden" name="place_location_lng" id="id_place_location_lng" />
        </div>
      </div>
    </form>
<br>
{% endblock %}

{% block customjs %}
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCDnACvF6RYeBiUBOjLgaTQAwPiN0ABVzU&sensor=false&libraries=places"></script>
    <script src="{% static 'events/googlemaps.js' %}"></script>

    <script>
      $(function(){
        $("#geocomplete").geocomplete({
          map: ".map_canvas",
          details: "form ",
          types: ["establishment"],
          markerOptions: {
            draggable: true
          }
        });


        $("#geocomplete").bind("geocode:dragged", function(event, latLng){
          $("input[name=place_location_lat]").val(latLng.lat());
          $("input[name=place_location_lng]").val(latLng.lng());
          $("input[name=place_text]").val("");
        });


        $("#find").click(function(){
          $("#geocomplete").trigger("geocode");
        }).click();
      });
    </script>
{% endblock %}

events/templates/events/index.html
{% extends "base.html" %}


{% block title %}Events list{% endblock %}

{% block content_title %}Events list{% endblock %}

{% block content %}

<style>

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}


</style>

<div class="input-group col-md-8">
      <input type="text" id="myInput" onkeyup="myFunction()" class="form-control rounded-0 py-2" placeholder="name of the event/tag">
      <span class="input-group-btn">
      </span>

        <script>
        function myFunction() {
        var input, filter, ul, li, a, b, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        ul = document.getElementById("myUL");
        li = ul.getElementsByTagName("li");
        for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("h5")[0];
        b = li[i].getElementsByTagName("h4")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        }
        else if(b.innerHTML.toUpperCase().indexOf(filter) > -1){
            li[i].style.display = "";
        } 
        else {
            li[i].style.display = "none";

        }
    }
}
</script>

            <i class="fa fa-search"></i>
      
</div>
<a role="button" class="btn btn-primary" href="{% url 'events:observing' %}">Show observed events</a>
<br>
<div class="doclona" id="doclonaid">
    <ul id="myUL">
        <div class="list-group" id="list-group">
            {% for event in events %}
                 <li>
                    <div class="1row" id="1rowid">
                        <a href="{% url 'events:details' event.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1" id="event.name" >{{event.name}}</h5>
                                <small>{{ event.start_date.day }}-{{ event.start_date.month }}-{{ event.start_date.year }}</small>
                            </div>
                            <p class="mb-1">
                            {{event.description}}
                            </p>
                            <h4 class="mb-1" id="event.tag" hidden>
                                {{event.tags.names}}
                            </h4>
                        </a>
                    </div>
                 </li>
            {% endfor %}
            {% if events.has_other_pages %}
              <ul class="pagination">
                {% if events.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ events.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                {% endif %}
                {% for i in events.paginator.page_range %}
                    {% if events.number == i %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if events.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ events.next_page_number }}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
                {% endif %}
              </ul>
            {% endif %}
        </div>
    </ul>
</div>
<br>
<a role="button" class="btn btn-primary" href="{% url 'events:create' %}">Add new event
</a>


{% endblock %}

events/templates/events/observing.html
{% extends "base.html" %}


{% block title %}Events list{% endblock %}

{% block content_title %}Events list{% endblock %}

{% block content %}

<style>

#myUL {
  list-style-type: none;
  padding: 0;
  margin: 0;
}


</style>

<div class="input-group col-md-8">
    <input type="text" id="myInput" onkeyup="myFunction()" class="form-control rounded-0 py-2" placeholder="name of the event/tag">
    <span class="input-group-btn">
    </span>
    <script>
        function myFunction() {
            var input, filter, ul, li, a, b, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            ul = document.getElementById("myUL");
            li = ul.getElementsByTagName("li");
            for (i = 0; i < li.length; i++) {
                a = li[i].getElementsByTagName("h5")[0];
                b = li[i].getElementsByTagName("h4")[0];
                if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    li[i].style.display = "";
                }
                else if(b.innerHTML.toUpperCase().indexOf(filter) > -1){
                    li[i].style.display = "";
                }
                else {
                    li[i].style.display = "none";

                }
            }
        }
    </script>
    <i class="fa fa-search"></i>
</div>
<br>

<div id="demo"><p></p></div>
<br>


<div class="doclona" id="doclonaid">
    <ul id="myUL">
      <div class="list-group" id="list-group">
        {% for event in events %}
        <li>
          <div class="1row" id="1rowid">
            <a href="{% url 'events:details' event.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1" id="event.name" >{{event.name}}</h5>
                <small>{{ event.start_date.day }}-{{ event.start_date.month }}-{{ event.start_date.year }}</small>
              </div>
              <p class="mb-1">
                {{event.description}}
              </p>
              <h4 class="mb-1" id="event.tag" hidden>
                {{event.tags.names}}
              </h4>
           </a>
         </div>
        </li>
        {% endfor %}
      </div>
    </ul>
</div>


{% endblock %}