czaswolny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.forms import *
from userena import views as userena_views
from reputation import views as reputation_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/signup/$', userena_views.signup, {'signup_form': SignupFormExtra}, name='userena_signup'),
    url(r'^accounts/signin/$', userena_views.signin, {'auth_form': AuthenticationFormExtra}, name='userena_signin'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/edit/$', userena_views.profile_edit, {'edit_profile_form': EditProfileFormExtra}, name='userena_profile_edit'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/$', reputation_views.show_received, name='reputation_show_received'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/given/$', reputation_views.show_given, name='reputation_show_given'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/add/$', reputation_views.add, name='reputation_add'),
    url(r'^accounts/', include('userena.urls')),
    url(r'^events/', include('events.urls'), name='events'),
    url(r'^accounts/addfriend/(?P<pk>[0-9]+)/$', views.addfriend, name='addfriend'),
    url(r'^accounts/invite/(?P<pk>[0-9]+)/$', views.invite, name='invite'),
    url(r'^accounts/refuseinvite/(?P<pk>[0-9]+)/$', views.refuseinvite, name='refuseinvite'),
    url(r'^accounts/unfriend/(?P<pk>[0-9]+)/$', views.unfriend, name='unfriend'),
    url(r'^accounts/uninvite/(?P<pk>[0-9]+)/$', views.uninvite, name='uninvite'),
    url(r'^posts/', include('posts.urls'), name='posts'),
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^observing/$', views.observing, name='observing'),
    url(r'^show/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^destroy/(?P<pk>[0-9]+)/$', views.destroy, name='destroy'),
    url(r'^join/(?P<pk>[0-9]+)/$', views.join, name='join'),
    url(r'^leave/(?P<pk>[0-9]+)/$', views.leave, name='leave'),
    url(r'^observe/(?P<pk>[0-9]+)/$', views.observe, name='observe'),
    url(r'^stopobserving/(?P<pk>[0-9]+)/$', views.stop_observing, name='stop_observing'),
    url(r'^block/(?P<pk>[0-9]+)/(?P<user_id>[0-9]+)/$', views.block, name='block'),
    url(r'^unblock/(?P<pk>[0-9]+)/(?P<user_id>[0-9]+)/$', views.unblock, name='unblock'),
    url(r'^create/$', views.create, name='create'),
    url(r'^like/(?P<pk>[0-9]+)/$', views.like, name='like'),
    url(r'^unlike/(?P<pk>[0-9]+)/$', views.unlike, name='unlike'),

]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/(?P<pk>[0-9]+)/$', views.create, name='create'),
    url(r'^show/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^destroy/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.destroy, name='destroy'),
    url(r'^destroycomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/(?P<pk3>[0-9]+)/$', views.destroycomment, name='destroycomment'),
    url(r'^createcomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.createcomment, name='createcomment'),
    url(r'^like/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.like, name='like'),
    url(r'^unlike/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.unlike, name='unlike'),

]

templates/_profile_navigation.html
<div class="">
  {% if user.username == profile.user.username %}
      {% block profile_navigation_items %}
        <a class="btn btn-primary" href="{% url 'userena_profile_detail' user.username %}">View profile</a>
        <a class="btn btn-primary" href="{% url 'userena_profile_edit' user.username %}">Edit profile</a>
        <a class="btn btn-primary" href="{% url 'userena_password_change' user.username %}">Change password</a>
        <a class="btn btn-primary" href="{% url 'userena_email_change' user.username %}">Change email</a>
      {% endblock %}
  {% else %}
      <a class="btn btn-primary" href="{% url 'reputation_add' profile.user.username %}">Add reputation</a></li>
  {% endif %}
  <a class="btn btn-primary"href="{% url 'reputation_show_received' profile.user.username %}">Received reputation</a>
  <a class="btn btn-primary"href="{% url 'reputation_show_given' profile.user.username %}">Given reputation</a>
</div>

templates/about.html
{% extends "base.html" %}

{% block title %}About, zalogowany{% endblock %}

{% block content %}
O stronie (zalogowany)...<br>
{{user.email}}<br>
{{user.my_profile.favourite_snack}}<br>
{{usernm}}
<p><h1>Opis projektu grupowego do organizacji czasu wolnego.</h1></p><br>
<p><i>Główną funkcjonalnością aplikacji byłaby aranżacja spotkań między użytkownikami systemu.<br><br>

Osoba zainteresowana aplikacją, powinna w pierwszej kolejności zarejestrować się, wypełniając pola formularza rejestracyjnego. Formularz będzie zawierał podstawowe dane o użytkowniku, takie jak imię, nazwisko, płeć, wiek, e-mail. Po zakończonej rejestracji, będziemy mogli logować się do aplikacji za pomocą e-maila/loginu i hasła. Każdy zarejestrowany użytkownik będzie miał swój profil, gdzie będą znajdowały się szczegółowe informacje na jego temat.<br><br>

Użytkownik, chcący zorganizować swój czas wolny, tworzy w aplikacji wydarzenie, przykładowo wybiera, że chciałby pójść do klubu gwint w okolicach 21:00, 10 października 2017. Oczywiście przydałaby się jakaś osoba lub grupa osób do towarzystwa. Taki użytkownik ma możliwość ustawienia w ile osób chce się udać w to miejsce , lub wyszukać a następnie dołączyć do istniejącego wydarzenia ( o ile znajdują się wolne miejsca). Osoba zakładająca wydarzenie ma możliwość ingerencji w to z kim uda się w wybrane miejsce. Użytkownicy którzy są przypisani do danego wydarzenia , mają możliwość prowadzenia konwersacji pod wydarzeniem.System pozwala na anulowanie spotkania(mogą zostać odjęte punkty, aby taki incydent więcej się nie powtarzał).<br><br>

Oczywiście możliwości spotkań jest bardzo dużo, od spotkań w plenerze aż po teatry/wesela.<br><br>
</i></p>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
{% load notification_tags %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    {% block customcss %}{% endblock %}
</head>

<body>
    <div class="wrapper">
	{% with url_name=request.resolver_match.url_name %}
        <div class="sidebar" data-color="blue">
            <div class="logo">
                <a href="/" class="simple-text">
                    Czas Wolny
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li {% if url_name == 'home' %}class="active"{% endif %}>
                        <a href="/">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li {% if url_name == 'userena_profile_detail' %} class="active"{% endif %}>
                        <a href="{% url 'userena_profile_detail' user.username %}">
                            <i class="material-icons">person</i>
                            <p>Profile</p>
                        </a>
                    </li>
                    <li {% if url_name == 'index' %} class="active" {% endif %}>
                        <a href="{% url 'events:index' %}">
                            <i class="material-icons">people</i>
                            <p>Events</p>
                        </a>
                    </li>
                    <li {% if url_name == 'userena_umessages_list' %} class="active"{% endif %}>
                        <a href="{% url 'userena_umessages_list' %}">
                            <i class="material-icons">chat</i>
                            <p>Messages</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand">{% block content_title %}{% endblock %}</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">notifications</i>
                                    <span class="notifications-unread-count"></span>
                                    <p class="hidden-lg hidden-md">Notifications</p>
                                </a>
                                <ul class="notification-box-list dropdown-menu dropdown-menu-right">
                                    {% render_notifications using user.notifications.active.prefetch for box %}
                                    <li class="dropdown-item">
                                        <a href="{% url 'notifications:all' %}">All Notifications</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'userena_signout' %}">
                                    <i class="material-icons">close</i>
                                    <p class="hidden-lg hidden-md">Sign Out</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group  is-empty">
                                <input type="text" class="form-control" placeholder="Search">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <div class="content">
                 {% if messages %}
                      <ul>
                        {% for message in messages %}
                        <div class="alert alert-info fade in">
                            <a href="#" class="close" data-dismiss="alert">&times;</a>
                            {{ message }}
                        </div>
                        {% endfor %}
                      </ul>
                    {% endif %}
                <div class="container-fluid">
				    {% block content %}{% endblock %}

                </div>
            </div>
        </div>
    </div>
	{% endwith %}
</body>
<!--   Core JS Files   -->
<script src="{% static 'javascript/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'javascript/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'javascript/material.min.js' %}" type="text/javascript"></script>
<!--  Dynamic Elements plugin -->
<script src="{% static 'javascript/arrive.min.js' %}"></script>
<!--  PerfectScrollbar Library -->
<script src="{% static 'javascript/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'javascript/bootstrap-notify.js' %}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'javascript/material-dashboard.js' %}"></script>
{% include_notify_js_variables %}
<script src="{% static 'notify/notifyX.js' %}"></script>
{% block customjs %}{% endblock %}
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Strona główna, zalogowany{% endblock %}
{% block content_title %}
    Dashboard
{% endblock %}

{% block content %}
    <style>

    #myUL {
      list-style-type: none;
      padding: 0;
      margin: 0;
    }


    </style>
    <h2>Your Events</h2>
    <div class="doclona" id="doclonaid">
        <ul id="myUL">
          <div class="list-group" id="list-group">
          {% for event in events %}
          <li>
            <div class="1row" id="1rowid">
              <a href="{% url 'events:details' event.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1" id="event.name" >{{event.name}}</h5>
                  <small>{{ event.start_date.day }}-{{ event.start_date.month }}-{{ event.start_date.year }}</small>
              </div>
              <p class="mb-1">
              {{event.description}}
              </p>
              <h4 class="mb-1" id="event.tag" hidden>
              {{event.tags.names}}
              </h4>
             </a>
           </div>
          </li>
          {% endfor %}
              </div>
        </ul>
    </div>
    {% if request.user.my_profile.ban == 2 %}
        Your account has been banned
{% endif %}
{% endblock %}

templates/navbar.html
{% with url_name=request.resolver_match.url_name %}
<!-- Icon Bar (Sidebar - hidden on small screens) -->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
    <!-- Avatar image in top left corner -->
    <img src="{{ user.my_profile.get_mugshot_url }}" style="width:100%">
    <a href="/" class="w3-bar-item w3-button w3-padding-large {% if url_name == 'home' %}w3-black{% else %}w3-hover-black{% endif %}">
        <i class="fa fa-home w3-xxlarge"></i>
        <p>HOME</p>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'userena_profile_detail' user.username %}" class="w3-bar-item w3-button w3-padding-large {% if url_name == 'userena_profile_detail' %}w3-black{% else %}w3-hover-black{% endif %}">
        <i class="fa fa-user w3-xxlarge"></i>
        <p>PROFILE</p>

    </a>
    {% endif %}
    <a href="{% url 'events:index' %}" class="w3-bar-item w3-button w3-padding-large {% if url_name == 'index' %}w3-black{% else %}w3-hover-black{% endif %}">
        <i class="fa fa-users w3-xxlarge"></i>
        <p>EVENTS</p>
    </a>
    <a href="{% url 'userena_umessages_list' %}" class="w3-bar-item w3-button w3-padding-large {% if url_name == 'userena_umessages_list' %}w3-black{% else %}w3-hover-black{% endif %}">
        <i class="fa fa-envelope w3-xxlarge"></i>
        <p>MESSAGES</p>
    </a>
    <a href="{% url 'userena_signout' %}" class="w3-bar-item w3-button w3-padding-large {% if url_name == 'userena_signout' %}w3-black{% else %}w3-hover-black{% endif %}">
        <i class="fa fa-sign-out w3-xxlarge"></i>
        <p>SIGN OUT</p>
    </a>
</nav>
{% endwith %}
<!-- Navbar on small screens (Hidden on medium and large screens) -->
<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
    <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
        <a href="{% url 'home' %}" class="w3-bar-item w3-button" style="width:20% !important">HOME</a>
        <a href="{% url 'userena_profile_detail' user.username %}" class="w3-bar-item w3-button" style="width:20% !important">PROFILE</a>
        <a href="{% url 'events:index' %}" class="w3-bar-item w3-button" style="width:20% !important">EVENTS</a>
        <a href="{% url 'userena_umessages_list' %}" class="w3-bar-item w3-button" style="width:20% !important">MESSAGES</a>
        <a href="{% url 'userena_signout' %}" class="w3-bar-item w3-button" style="width:20% !important">SIGN OUT</a>
    </div>
</div>