czaswolny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.forms import *
from userena import views as userena_views
from reputation import views as reputation_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/signup/$', userena_views.signup, {'signup_form': SignupFormExtra}, name='userena_signup'),
    url(r'^accounts/signin/$', userena_views.signin, {'auth_form': AuthenticationFormExtra}, name='userena_signin'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/edit/$', userena_views.profile_edit, {'edit_profile_form': EditProfileFormExtra}, name='userena_profile_edit'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/$', reputation_views.show_received, name='reputation_show_received'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/given/$', reputation_views.show_given, name='reputation_show_given'),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/reputation/add/$', reputation_views.add, name='reputation_add'),
    url(r'^accounts/', include('userena.urls')),
    url(r'^events/', include('events.urls'), name='events'),
    url(r'^accounts/addfriend/(?P<pk>[0-9]+)/$', views.addfriend, name='addfriend'),
    url(r'^accounts/invite/(?P<pk>[0-9]+)/$', views.invite, name='invite'),
    url(r'^accounts/refuseinvite/(?P<pk>[0-9]+)/$', views.refuseinvite, name='refuseinvite'),
    url(r'^accounts/unfriend/(?P<pk>[0-9]+)/$', views.unfriend, name='unfriend'),
    url(r'^accounts/uninvite/(?P<pk>[0-9]+)/$', views.uninvite, name='uninvite'),
    url(r'^posts/', include('posts.urls'), name='posts'),
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/(?P<pk>[0-9]+)/$', views.create, name='create'),
    url(r'^show/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^destroy/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.destroy, name='destroy'),
    url(r'^destroycomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/(?P<pk3>[0-9]+)/$', views.destroycomment, name='destroycomment'),
    url(r'^createcomment/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.createcomment, name='createcomment'),
    url(r'^like/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.like, name='like'),
    url(r'^unlike/(?P<pk2>[0-9]+)/(?P<pk>[0-9]+)/$', views.unlike, name='unlike'),

]

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Comment(models.Model):
    content = models.TextField(max_length=4000, blank=False)
    publish_date = models.DateTimeField(blank=False)
    author = models.ForeignKey(User, related_name="authorcomment")


class Post(models.Model):
    content = models.TextField(max_length=4000, blank=False)
    publish_date = models.DateTimeField(blank=False)
    author = models.ForeignKey(User, related_name="autorpost")
    comments = models.ManyToManyField(Comment)
    likes = models.ManyToManyField(User)

posts/forms.py
from django import forms

from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ('content', )
        labels = {
                  "content": "Post content",
                  }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        fields = ('content', )
        labels = {
                  "content": "Post content",
                  }

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from .models import *
from events.models import Event
from django.utils import timezone
from notify.signals import notify
from django.contrib.auth.decorators import login_required
from czaswolny.decorators import user_not_banned
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
@user_not_banned
def index(request):
    return render(request, 'posts/index.html')


@login_required
@user_not_banned
def create(request, pk):
    if request.method == "POST":
        event = get_object_or_404(Event, pk=pk)
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish_date = timezone.now()
            post.save()
            event.posts.add(post)
            return redirect('events:details', pk=event.pk)
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form': form})


@login_required
@user_not_banned
def createcomment(request, pk, pk2):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.publish_date = timezone.now()
            comment.save()
            post.comments.add(comment)
            if request.user != post.author:
                notify.send(request.user, recipient=post.author, actor=request.user, verb='commented your post.', nf_type='post_commented')
            return redirect('posts:details', pk=post.pk, pk2=pk2)
    else:
        form = CommentForm()
    return render(request, 'posts/createcomment.html', {'form': form})


@login_required
@user_not_banned
def details(request, pk, pk2):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    if pk2 is None:
        return HttpResponseRedirect(reverse('events:index'))

    post = get_object_or_404(Post, pk=pk)
    event = get_object_or_404(Event, pk=pk2)
    comments_all = post.comments.all().order_by('-publish_date')

    # Paginacja co 5 odpowiedzi
    paginator = Paginator(comments_all, 5)
    page = request.GET.get('page', 1)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    return render(request, 'posts/details.html', {'post': post, 'event': event, 'comments': comments})


@require_POST
@login_required
@user_not_banned
def destroy(request, pk, pk2):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk2)
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.author:
        return HttpResponseRedirect(reverse('events:index'))

    post.delete()
    return redirect('events:details', pk=event.pk)


@require_POST
@login_required
@user_not_banned
def destroycomment(request, pk, pk2, pk3):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))
    if pk2 is None:
        return HttpResponseRedirect(reverse('events:index'))
    event = get_object_or_404(Event, pk=pk2)
    post = get_object_or_404(Post, pk=pk)
    comment = get_object_or_404(Comment, pk=pk3)

    if request.user != comment.author:
        return HttpResponseRedirect(reverse('events:index'))

    comment.delete()
    return redirect('posts:details', pk=post.pk, pk2=event.pk)


@require_POST
@login_required
@user_not_banned
def like(request, pk, pk2):
    if pk is None:
        return HttpResponseRedirect(reverse('posts:index'))

    post = get_object_or_404(Post, pk=pk)
    event = get_object_or_404(Event, pk=pk2)
    comments = post.comments.all()
    post.likes.add(request.user)

    return render(request, 'posts/details.html', {'post': post, 'event': event, 'comments': comments})


@require_POST
@login_required
@user_not_banned
def unlike(request, pk, pk2):
    if pk is None:
        return HttpResponseRedirect(reverse('events:index'))

    post = get_object_or_404(Post, pk=pk)
    event = get_object_or_404(Event, pk=pk2)
    comments = post.comments.all()
    post.likes.remove(request.user)

    return render(request, 'posts/details.html', {'post': post, 'event': event, 'comments': comments})

posts/templates/posts/create.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block title %}Tworzenie postu{% endblock %}
{% block content_title %}New Post{% endblock %}
{% block content %}

     <form method="POST" class="post-form">{% csrf_token %}

         <fieldset>
             <div class="form-group">
                 <label class="bmd-label-floating">Post content</label>
                 {{ form.content|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: Text" }}
             </div>
         </fieldset>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
<br>

{% endblock %}

posts/templates/posts/createcomment.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block title %}Tworzenie komentarza{% endblock %}
{% block content_title %}<h2>New Comment</h2>{% endblock %}
{% block content %}

     <form method="POST" class="post-form">{% csrf_token %}
         <fieldset>
             <div class="form-group">
                 <label class="bmd-label-floating">Comment content</label>
                 {{ form.content|add_class:"form-control rounded-0 py-2"|append_attr:"placeholder: Text" }}
             </div>
         </fieldset>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
<br>

{% endblock %}

posts/templates/posts/details.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Post details{% endblock %}

{% block content_title %}{{event.name}}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
        <div class="card card-profile">
            <div class="card-avatar">
                <img class="img" src="{{ post.author.my_profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
            </div>
            <div class="content">
                <h4 class="card-title">{{ post.author.username }}</h4>
            </div>
        </div>
        <div class="card card-stats">
            <div class="card-header" data-background-color="red">
                <i class="material-icons">favorite</i>
            </div>
            <div class="card-content">
                <p class="category">Likes</p>
                <h3 class="title">{{ post.likes.count }}</h3>
            </div>
            <div class="card-footer">
              {% if request.user in post.likes.all %}
                  <form class="btn-group btn-block" action="{% url 'posts:unlike' event.pk post.pk %}" method="POST">
                      {% csrf_token %}
                      <button class="btn btn-danger btn-block">Dislike</button>
                      <input type="hidden" class="btn btn-block"/>
                  </form>
              {% else %}
                  <form class="btn-group btn-block" action="{% url 'posts:like' event.pk post.pk %}" method="POST">
                      {% csrf_token %}
                      <button class="btn btn-primary btn-block">Like</button>
                      <input type="hidden" class="btn btn-block"/>
                  </form>
              {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-9">
      <div class="card">
          <div class="card-header">
              <h4 class="title">{{post.author.first_name}} {{post.author.last_name}}</h4>
          </div>

          <div class="card-content">
              {{post.content}}<br><br>
              <i class="material-icons ">favorite</i>
              {{ post.likes.count }}
              <small><em>{{ post.publish_date.day }}-{{ post.publish_date.month }}-{{ post.publish_date.year }}</em></small>

          </div>
      </div>
      {% ifequal user post.author %}
      <form action="{% url 'posts:destroy' event.pk post.pk %}" method="POST" class="col-md-2">
          {% csrf_token %}
          <input type="submit" role="button" class="btn btn-danger" value="Delete post"/>
      </form>
      {% endifequal %}
    </div>
  </div>
  <ul class="list-group">
  <h4 class="card-header">Comments</h4>
  {% for comment in comments %}

      <div class="list-group-item list-group-item-dark flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
          <div class="mb-1">
          <img src="{{ comment.author.my_profile.get_mugshot_url }}" style="width:35px">
              <b>{{comment.author}}</b>
  <div>{{comment.content}}
       </div>

          </div>

          <small>
              {% ifequal user comment.author %}
              <form action="{% url 'posts:destroycomment' event.pk post.pk comment.pk %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" role="button" class="btn btn-danger" value="Delete comment"/>
              </form>
              {% endifequal %} {{ comment.publish_date.day }}-{{ comment.publish_date.month }}-{{ comment.publish_date.year }}
          </small>
      </div>


     </div>
  {% endfor %}

  {% if comments.has_other_pages %}
    <ul class="pagination">
      {% if comments.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ comments.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>
      {% endif %}
      {% for i in comments.paginator.page_range %}
          {% if comments.number == i %}
          <li class="page-item active">
              <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if comments.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ comments.next_page_number }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
      </li>
      {% endif %}
    </ul>
  {% endif %}
  </ul>
  <a role="button" class="btn btn-primary" href="{% url 'posts:createcomment' event.pk post.pk %}">Add comment</a>

  {% endblock %}